version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=128MiB

  redis:
    image: redis:6.0.8-alpine
    ports:
      - 6379:6379
    networks:
      - network_transaction_conusmer
    volumes:
      - ./env/redis-config:/docker/config
      - redis-data:/data 

  postgres:
    image: postgres:12.4-alpine
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password 
        POSTGRES_DB: example
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - dbdata:/var/lib/postgresql/data
        - ./env/postgres-init:/docker-entrypoint-initdb.d
    ports:
        - 5432:5432  

volumes:
  dbdata:
  redis-data: 
  rabbitmq-data:   

networks:
  network_transaction_conusmer:
    external: false      