version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    networks:
      - network_transaction_conusmer
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=passwd
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=128MiB

  redis:
    image: redis:6.0.8-alpine
    networks:
      - network_transaction_conusmer
    ports:
      - 6379:6379
    volumes:
      - ./env/redis-config:/docker/config
      - redis-data:/data 

  postgres:
    image: postgres:12.4-alpine
    networks:
      - network_transaction_conusmer
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password 
        POSTGRES_DB: example
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - dbdata:/var/lib/postgresql/data
        - ./env/postgres-init:/docker-entrypoint-initdb.d
    ports:
        - 5432:5432  

  consumer-native:
    build: 
      context: transaction-consumer/
      dockerfile: Dockerfile.native
      args: 
        MAVEN_OPTS: -Djava.net.preferIPv4Stack=true
    volumes: 
      - mvn-repo:/usr/share/maven/ref/repository
    networks:
      - network_transaction_conusmer  
    ports: 
      - 8081:8080
    depends_on:
      - rabbitmq
      - redis
      - postgres

  consumer-hotspot:
    build: 
      context: transaction-consumer/
      dockerfile: Dockerfile
    volumes: 
      - mvn-repo:/usr/share/maven/ref/repository
    networks:
      - network_transaction_conusmer
    ports: 
      - 8080:8080
    depends_on:
      - rabbitmq
      - redis
      - postgres

volumes:
  mvn-repo:
  dbdata:
  redis-data: 
  rabbitmq-data:   

networks:
  network_transaction_conusmer:
    external: false